target 'WatchOn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchOn
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'PromiseKit', '6.8.4'
  pod 'SwiftKeychainWrapper', '3.2.0'
  pod 'SkeletonView', '1.4.2'
  pod 'lottie-ios', '3.0.4'
  pod 'ReachabilitySwift'
  pod 'SwiftyJSON'
  pod 'Nuke'
  pod 'Toucan'
  
  target 'WatchOnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WatchOnUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if config.name == 'Debug'
                  config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                  config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
              end
          end
      end
  end

end
